/** @type {import('next').NextConfig} */
const securityHeaders = [
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), payment=()' },
  { key: 'Content-Security-Policy', value: "frame-ancestors 'self'; base-uri 'self'; object-src 'none'; form-action 'self'" },
]

const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  async headers() {
    return [{ source: '/:path*', headers: securityHeaders }]
  },
  // Keep rankings: the old WordPress site served articles at /<slug>/ and pages at their own paths.
  async redirects() {
    return [
      { source: '/free-trial', destination: '/trial', permanent: true },
      { source: "/home-2", destination: "/reseller", permanent: true },
      { source: "/installation-guide", destination: "/install", permanent: true },
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/terms-and-conditions", destination: "/legal/terms", permanent: true },
      { source: "/refund-and-cancellation-policy", destination: "/legal/refund", permanent: true },
      { source: "/shop", destination: "/#plans", permanent: true },
      { source: "/cart", destination: "/#plans", permanent: true },
      { source: "/checkout", destination: "/#plans", permanent: true },
      { source: "/my-account", destination: "/", permanent: true },
      { source: "/best-iptv-services-for-firestick-in-usa-2026", destination: "/blog/best-iptv-for-firestick-usa", permanent: true },
      { source: "/iptv-what-is-it-guide", destination: "/blog/iptv-what-is-it-guide", permanent: true },
      { source: "/iptv-services-the-ultimate-guide-to-best-streaming", destination: "/blog/iptv-services-the-ultimate-guide-to-best-streaming", permanent: true },
      { source: "/iptv-providers-ultimate-guide", destination: "/blog/iptv-providers-ultimate-guide", permanent: true },
      { source: "/iptv-free-trial-expansion-plan", destination: "/iptv-subscription", permanent: true },
      { source: "/iptv-smart-player-expansion-plan", destination: "/blog/iptv-smart-player-expansion-plan", permanent: true },
      { source: "/iptv-encoder-unlock-entertainment-future", destination: "/blog/iptv-encoder-unlock-entertainment-future", permanent: true },
      { source: "/iptv-box-entertainment-solution", destination: "/blog/iptv-box-entertainment-solution", permanent: true },
      { source: "/best-iptv-services-2", destination: "/blog/best-iptv-services-2", permanent: true },
      { source: "/iptv-service-expansion-plan-2026", destination: "/blog/iptv-service-expansion-plan-2026", permanent: true },
      { source: "/what-is-iptv-guide", destination: "/blog/what-is-iptv-guide", permanent: true },
      { source: "/iptv-smarters-ultimate-guide-2026", destination: "/blog/iptv-smarters-ultimate-guide-2026", permanent: true },
      { source: "/iptv-encoder-box-streaming-guide", destination: "/blog/iptv-encoder-box-streaming-guide", permanent: true },
      { source: "/best-iptv-apps-usa", destination: "/blog/best-iptv-apps-usa", permanent: true },
      { source: "/customer-reviews-usa-iptv-guide", destination: "/blog/customer-reviews-usa-iptv-guide", permanent: true },
      { source: "/best-iptv-subscription-usa-2025", destination: "/blog/best-iptv-subscription-usa-2025", permanent: true },
      { source: "/buy-iptv-usa-now-2026-guide", destination: "/blog/buy-iptv-usa-now-2026-guide", permanent: true },
      { source: "/iptv-not-working-usa-fix", destination: "/blog/iptv-not-working-usa-fix", permanent: true },
      { source: "/iptv-buffering-fix-usa", destination: "/blog/iptv-buffering-fix-usa", permanent: true },
      { source: "/iptv-florida-2026-guide", destination: "/blog/iptv-florida-2026-guide", permanent: true },
      { source: "/iptv-texas-best-iptv-service-2026", destination: "/blog/iptv-texas-best-iptv-service-2026", permanent: true },
      { source: "/iptv-california", destination: "/blog/iptv-california", permanent: true },
      { source: "/tivimate-iptv-usa-guide-2", destination: "/blog/tivimate-iptv-usa-guide-2", permanent: true },
      { source: "/iptv-smarters-pro-usa-setup", destination: "/blog/iptv-smarters-pro-usa-setup", permanent: true },
      { source: "/iptv-for-smart-tv-usa", destination: "/blog/iptv-for-smart-tv-usa", permanent: true },
      { source: "/iptv-for-roku-usa", destination: "/blog/iptv-for-roku-usa", permanent: true },
      { source: "/best-iptv-for-firestick-usa", destination: "/blog/best-iptv-for-firestick-usa", permanent: true },
      { source: "/cheap-iptv-usa", destination: "/blog/cheap-iptv-usa", permanent: true },
      { source: "/iptv-free-trial-usa-guide", destination: "/iptv-subscription", permanent: true },
      { source: "/is-iptv-legal-in-the-usa", destination: "/blog/is-iptv-legal-in-the-usa", permanent: true },
      { source: "/best-iptv-service-usa-the-2026-buyers-guide-legal-safe", destination: "/blog/best-iptv-service-usa-the-2026-buyers-guide-legal-safe", permanent: true },
      { source: "/top-iptv-usa", destination: "/blog/top-iptv-usa", permanent: true },
      { source: "/best-iptv-usa-2", destination: "/blog/best-iptv-usa-2", permanent: true },
      { source: "/best-iptv-usa-2025", destination: "/blog/best-iptv-usa-2025", permanent: true },
      { source: "/best-iptv-usa", destination: "/blog/best-iptv-usa", permanent: true },
      { source: "/iptv-subscription-usa", destination: "/blog/iptv-subscription-usa", permanent: true },
      { source: "/iptv-usa-guide", destination: "/blog/iptv-usa-guide", permanent: true },
      { source: "/what-is-iptv-service-2", destination: "/blog/what-is-iptv-service-2", permanent: true },
      { source: "/how-much-does-iptv-cost", destination: "/blog/how-much-does-iptv-cost", permanent: true },
      { source: "/what-is-the-best-iptv-service", destination: "/blog/what-is-the-best-iptv-service", permanent: true },
      { source: "/is-iptv-legal-in-the-united-states", destination: "/blog/is-iptv-legal-in-the-united-states", permanent: true },
      { source: "/iptv-services-legal-guide", destination: "/blog/iptv-services-legal-guide", permanent: true },
      { source: "/iptv-service-troypoint-guide", destination: "/blog/iptv-safety-tips", permanent: true },
      { source: "/iptv-subscription-pro", destination: "/blog/iptv-subscription-pro", permanent: true },
      { source: "/smartiflix-iptv", destination: "/blog/iptv-streaming-services", permanent: true },
      { source: "/iptv-streaming-services-2", destination: "/blog/iptv-streaming-services-2", permanent: true },
      { source: "/best-iptv-services-reddit", destination: "/blog/best-iptv-services-reddit", permanent: true },
      { source: "/best-iptv-service-2026", destination: "/blog/best-iptv-service-2026", permanent: true },
      { source: "/iptv-free-trial-usa-2025", destination: "/iptv-subscription", permanent: true },
      { source: "/best-iptv-subscription-deals-2025", destination: "/blog/best-iptv-subscription-deals-2025", permanent: true },
      { source: "/iptv-subscription-cost-2025", destination: "/blog/iptv-subscription-cost-2025", permanent: true },
      { source: "/monthly-iptv-subscription-vs-annual", destination: "/blog/monthly-iptv-subscription-vs-annual", permanent: true },
      { source: "/iptv-subscription-legal-2025", destination: "/blog/iptv-subscription-legal-2025", permanent: true },
      { source: "/iptv-subscription-firestick-2", destination: "/blog/iptv-subscription-firestick-2", permanent: true },
      { source: "/buy-iptv-subscription-safely-2025", destination: "/blog/buy-iptv-subscription-safely-2025", permanent: true },
      { source: "/cheap-iptv-service-under-5", destination: "/blog/cheap-iptv-service-under-5", permanent: true },
      { source: "/cheap-iptv-subscriptions", destination: "/blog/cheap-iptv-subscriptions", permanent: true },
      { source: "/premium-iptv-subscription", destination: "/blog/premium-iptv-subscription", permanent: true },
      { source: "/iptv-subscription-guide-2", destination: "/blog/iptv-subscription-guide-2", permanent: true },
      { source: "/iptv-provider-comparison-2025", destination: "/blog/iptv-provider-comparison-2025", permanent: true },
      { source: "/best-iptv-provider-reviews-2025", destination: "/blog/best-iptv-provider-reviews-2025", permanent: true },
      { source: "/iptv-platform-providers-2025", destination: "/blog/iptv-platform-providers-2025", permanent: true },
      { source: "/how-to-become-iptv-provider-2025", destination: "/blog/how-to-become-iptv-provider-2025", permanent: true },
      { source: "/reliable-iptv-providers-2025", destination: "/blog/reliable-iptv-providers-2025", permanent: true },
      { source: "/legal-iptv-providers-2025", destination: "/blog/legal-iptv-providers-2025", permanent: true },
      { source: "/iptv-server-providers", destination: "/blog/iptv-server-providers", permanent: true },
      { source: "/arabic-iptv-providers-2025", destination: "/blog/arabic-iptv-providers-2025", permanent: true },
      { source: "/best-iptv-providers-uk-2025", destination: "/blog/best-iptv-providers-uk-2025", permanent: true },
      { source: "/best-iptv-providers-usa-2025", destination: "/blog/best-iptv-providers-usa-2025", permanent: true },
      { source: "/iptv-providers-2", destination: "/blog/iptv-providers-2", permanent: true },
      { source: "/top-10-iptv-services-2025", destination: "/blog/top-10-iptv-services-2025", permanent: true },
      { source: "/reddit-best-iptv-2025", destination: "/blog/reddit-best-iptv-2025", permanent: true },
      { source: "/cheap-iptv-services-2025", destination: "/blog/cheap-iptv-services-2025", permanent: true },
      { source: "/best-4k-iptv-services", destination: "/blog/best-4k-iptv-services", permanent: true },
      { source: "/best-iptv-for-firestick-2025", destination: "/blog/best-iptv-for-firestick-2025", permanent: true },
      { source: "/most-reliable-iptv-services", destination: "/blog/most-reliable-iptv-services", permanent: true },
      { source: "/best-paid-iptv-services", destination: "/blog/best-paid-iptv-services", permanent: true },
      { source: "/best-sports-iptv-services", destination: "/blog/best-sports-iptv-services", permanent: true },
      { source: "/top-rated-iptv-services-2025", destination: "/blog/top-rated-iptv-services-2025", permanent: true },
      { source: "/iptv-trends-2025", destination: "/blog/iptv-trends-2025", permanent: true },
      { source: "/best-iptv-sites", destination: "/blog/best-iptv-sites", permanent: true },
      { source: "/iptv-safety-tips", destination: "/blog/iptv-safety-tips", permanent: true },
      { source: "/legal-vs-illegal-iptv", destination: "/blog/legal-vs-illegal-iptv", permanent: true },
      { source: "/iptv-technology-explained", destination: "/blog/iptv-technology-explained", permanent: true },
      { source: "/reliable-iptv-services", destination: "/blog/reliable-iptv-services", permanent: true },
      { source: "/compare-iptv-services", destination: "/blog/compare-iptv-services", permanent: true },
      { source: "/types-of-iptv-services", destination: "/blog/types-of-iptv-services", permanent: true },
      { source: "/is-iptv-legal-2025", destination: "/blog/is-iptv-legal-2025", permanent: true },
      { source: "/iptv-4k", destination: "/blog/iptv-4k", permanent: true },
      { source: "/iptv-subscription-reddit", destination: "/blog/iptv-subscription-reddit", permanent: true },
      { source: "/iptv-subscription-firestick", destination: "/blog/iptv-subscription-firestick", permanent: true },
      { source: "/premium-iptv-services", destination: "/blog/premium-iptv-services", permanent: true },
      { source: "/free-vs-paid-iptv", destination: "/iptv-subscription", permanent: true },
      { source: "/arabic-iptv-providers", destination: "/blog/arabic-iptv-providers", permanent: true },
      { source: "/iptv-smarters-providers", destination: "/blog/iptv-smarters-providers", permanent: true },
      { source: "/best-legal-iptv-providers", destination: "/blog/best-legal-iptv-providers", permanent: true },
      { source: "/iptv-providers-reddit", destination: "/blog/iptv-providers-reddit", permanent: true },
      { source: "/4k-iptv-service", destination: "/blog/4k-iptv-service", permanent: true },
      { source: "/best-iptv-service-for-sports", destination: "/blog/best-iptv-service-for-sports", permanent: true },
      { source: "/top-iptv-services", destination: "/blog/top-iptv-services", permanent: true },
      { source: "/iptv-streaming-services", destination: "/blog/iptv-streaming-services", permanent: true },
      { source: "/buy-iptv-subscription-safely", destination: "/blog/buy-iptv-subscription-safely", permanent: true },
      { source: "/cheap-iptv-subscription", destination: "/blog/cheap-iptv-subscription", permanent: true },
      { source: "/best-iptv-subscription", destination: "/blog/best-iptv-subscription", permanent: true },
      { source: "/iptv-subscription-guide", destination: "/blog/iptv-subscription-guide", permanent: true },
      { source: "/best-iptv-service-for-firestick", destination: "/blog/best-iptv-service-for-firestick", permanent: true },
      { source: "/how-to-become-iptv-provider", destination: "/blog/how-to-become-iptv-provider", permanent: true },
      { source: "/iptv-providers-uk", destination: "/blog/iptv-providers-uk", permanent: true },
      { source: "/top-iptv-providers-usa", destination: "/blog/top-iptv-services", permanent: true },
      { source: "/iptv-providers", destination: "/blog/iptv-providers", permanent: true },
      { source: "/best-iptv-service-for-tivimate", destination: "/blog/best-iptv-service-for-tivimate", permanent: true },
      { source: "/best-iptv-service-reddit", destination: "/blog/best-iptv-service-reddit", permanent: true },
      { source: "/best-iptv-services", destination: "/blog/best-iptv-services", permanent: true },
      { source: "/cheap-iptv-service", destination: "/blog/cheap-iptv-service", permanent: true },
      { source: "/iptv-services-legal-what-you-need-to-know", destination: "/blog/iptv-services-legal-what-you-need-to-know", permanent: true },
      { source: "/what-is-iptv-service", destination: "/blog/what-is-iptv-service", permanent: true },
      { source: "/iptv-services-guide", destination: "/blog/iptv-services-guide", permanent: true },
      { source: "/iptv-guide", destination: "/blog/iptv-guide", permanent: true },
      { source: "/evolution-of-iptv", destination: "/blog/evolution-of-iptv", permanent: true },
    ]
  },
}

export default nextConfig
